---
abstract: 'RBAC DB realization'
author:
  - 'Sergei Svistunov <sergei-svistunov@yandex.ru>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.039, CPAN::Meta::Converter version 2.143240'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: QBit-Application-Model-RBAC-DB
requires:
  QBit::Application::Model::DB: 0
  QBit::Application::Model::RBAC: 0
  base: 0
  qbit: 0
version: 0.002
